---
#Inicio del equivalente del secure_installation
- name: Start the MySQL service
  action: service name=mysqld state=started

  #
- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Ensure there arent anonymous users in the database
  mysql_user: name='' host=$item state=absent
  with_items:
    - localhost
    - $inventory_hostname

- name: Remove the test database
  mysql_db: name=test state=absent

#Abajo se puede incluir acciones de manejo de usuarios y bases de datos